services:
  app:
    build: .
    container_name: lotogiro
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - ./app:/var/www/html/app
      - ./resources:/var/www/html/resources
      - ./routes:/var/www/html/routes
      - ./bootstrap:/var/www/html/bootstrap
    network_mode: bridge