CREATE TABLE IF NOT EXISTS `bichao_games` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `modalidade_id` int(11) DEFAULT NULL,
  `client_id` bigint(20) unsigned NOT NULL,
  `user_id` bigint(20) unsigned NOT NULL,
  `horario_id` int(11) DEFAULT NULL,
  `valor` float DEFAULT NULL,
  `comission_percentage` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `comission_value` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `comission_payment` tinyint(1) DEFAULT NULL,
  `comission_value_pai` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `game_1` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `game_2` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `game_3` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `premio_1` tinyint(1) DEFAULT 0,
  `premio_2` tinyint(1) DEFAULT 0,
  `premio_3` tinyint(1) DEFAULT 0,
  `premio_4` tinyint(1) DEFAULT 0,
  `premio_5` tinyint(1) DEFAULT 0,
  `criado_em` datetime DEFAULT curdate(),
  `updated_at` datetime DEFAULT curdate(),
  PRIMARY KEY (`id`),
  KEY `fk_game_cliente` (`client_id`),
  KEY `fk_game_modalidade` (`modalidade_id`),
  KEY `fk_game_horario` (`horario_id`),
  KEY `fk_game_user` (`user_id`),
  CONSTRAINT `fk_game_cliente` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_game_horario` FOREIGN KEY (`horario_id`) REFERENCES `bichao_horarios` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_game_modalidade` FOREIGN KEY (`modalidade_id`) REFERENCES `bichao_modalidades` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_game_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=53 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;